name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey There, This is your first issue in this repo. We will respond very fast.'
        pr-message: 'Hey There, This is your pull request in this repo. We will respond very fast.'
